#!/usr/bin/env python

from sikuli.Sikuli import Screen, Pattern, Location
import time

scr = Screen()
origin = Pattern(psc)
offset = origin.targetOffset(int(x),int(y))
scr.click(offset)
time.sleep(1)
